OpenSMTPD/OpenSMTPD

- smtpd/smtp_session.c
Reverts OpenSMTPD/OpenSMTPD#511
> Revert "Too much ; in Received: headers"

- smtpd/smtp_session.c
> Single semicolon in Received line

- smtpd/aliases.5
- smtpd/forward.5
- smtpd/lka_session.c
- smtpd/smtpd.h
- smtpd/to.c
> Implement maildir:/path expansion in aliases and forward file.

- smtpd/makemap.8
- smtpd/smtpd.8
1. Line-continuation and comments for makemap input
2. Add missing -T trace option of smtpd
> Improve man-pages

- smtpd/smtpd.c
Also log what signal was received.
> Die gracefully after receiving SIGTERM or SIGINT

- smtpd/control.c
- smtpd/smtpctl.c
> fix sun identifier

- smtpd/to.c
> useless include fts

- smtpd/aliases.c
Only relevant commit is f5793a0d8e5278604e6834d251e8e0d4876d909f
> TAG_CHAR fixes

- configure.ac
> check flock

- openbsd-compat/defines.h
- openbsd-compat/openbsd-compat.h
add some define if not have flock
> add defines if not have flock

- configure.ac
> Allow configure to change where the pidfile goes

- configure.ac
- remove extra space before ';'
- use '-a' instead ' && test '
- remove useless 'x' when $withval is not empty
> fix test usage:

- configure.ac
- openbsd-compat/Makefile.am
Fix tabs/spaces
Don't build function in compat if system support it
> Fix tabs/spaces, build function

- configure.ac
> functions already checked with AC_SEARCH_LIBS

- configure.ac
- openbsd-compat/Makefile.am
- openbsd-compat/explicit_bzero.c
check for support
build if neeeded
sync with latest OpenBSD
> Explicit bzero

- configure.ac
- openbsd-compat/defines.h
> check declaration of SSL_OP_NO_CLIENT_RENEGOTIATION

- README.md
I just stumbled on the wording of this sentence, so here is a small rewording.
Hope that helps!
> Make advice to use two users less ambiguous

- configure.ac
- openbsd-compat/Makefile.am
- openbsd-compat/crypt_checkpass.c
- openbsd-compat/openbsd-compat.h
wrapper arround crypt_checkpass
> Crypt checkpass wrapper

- configure.ac
> check function getpeerucred

- mk/smtpd/Makefile.am
fix ld fatal symbol referencing errors
> fix smtpd sources

- openbsd-compat/bsd-err.c
add check for NULL fmt
add warnx
> import from openssh

- configure.ac
- openbsd-compat/Makefile.am
- openbsd-compat/openbsd-compat.h
- openbsd-compat/strndup.c
- openbsd-compat/strnlen.c
> fix strndup

- Dockerfile
Discussed in https://github.com/OpenSMTPD/OpenSMTPD/issues/947
> add /var/mail dir to container

- etc/README.md
- etc/aliases
Closes https://github.com/OpenSMTPD/OpenSMTPD/issues/949
> add default aliases file

- docker/Dockerfile.archlinux
Archlinux build with glibc, libressl, gcc
> docker: archlinux build

- .gitignore
- ci/README.md
- ci/scripts/generate_certs.sh
- ci/scripts/ssl.conf
Handy script if you need to generate TLS certs quickly for testing
> ci: handy cert generation script

- ci/scripts/coverity_scan.sh
I got tired of shitty Coverity Scan service. Half of the times build gets submitted to the "bad worked" and sits there forever. 
I noticed a correlation that whenever that happens curl returns a big html page instead of short "Build submitted successfully" 
Example:
https://github.com/OpenSMTPD/OpenSMTPD/commit/43b4d4483edfcffd4370f91bd43bf8be502008de/checks?check_suite_id=297461257
This little tweak is supposed to fail the workflow in this case so we get notified.  (So I can go cancel the build manually)
> ci: fail if coverity scan was not submitted sucessfully

- README.md
- add version badge
- add license badge
> doc: moar badges

- configure.ac
- openbsd-compat/Makefile.am
- openbsd-compat/fgetln.c
- openbsd-compat/freezero.c
- openbsd-compat/pw_dup.c
- openbsd-compat/reallocarray.c
- openbsd-compat/setresgid.c
- openbsd-compat/setresuid.c
- openbsd-compat/strlcat.c
- openbsd-compat/strlcpy.c
- openbsd-compat/strmode.c
- smtpd/control.c
conditionally ifdef out bits as explained in #988 
This does not fully fix the issue, it only solves the easiest bits for now.
> convert most of openbsd-compat to conditional build rather than

- .github/workflows/clang.yml
- README.md
> ci: clang scan workflow

- .builds/openbsd.yml
- openbsd-compat/err_h/err.h
- openbsd-compat/openbsd-compat.h
- usr.sbin/smtpd/smtpd.c
I've edit smtpd.c maybe I need to open a contrib on OpenBSD for this one?
I can create a dedicated pull request for the source hub ci patch too.
> Fix macos build

- configure.ac
- openbsd-compat/openbsd-compat.h
- usr.sbin/smtpd/config.c
- usr.sbin/smtpd/parse.y
- usr.sbin/smtpd/smtpctl.c
> Fix missing include

- openbsd-compat/libasr/asr.c
- usr.sbin/smtpd/ca.c
- usr.sbin/smtpd/dispatcher.c
- usr.sbin/smtpd/mta.c
- usr.sbin/smtpd/mta_session.c
- usr.sbin/smtpd/parse.y
- usr.sbin/smtpd/smtp.c
- usr.sbin/smtpd/smtpctl.c
- usr.sbin/smtpd/smtpd-filters.7
- usr.sbin/smtpd/smtpd.c
- usr.sbin/smtpd/smtpd.conf.5
- usr.sbin/smtpd/smtpd.h
- usr.sbin/smtpd/smtpd/Makefile
- usr.sbin/smtpd/ssl.c
- usr.sbin/smtpd/ssl.h
- usr.sbin/smtpd/unpack_dns.c
I’ve cherry-picked all relevant commits with changes in `usr.sbin/smtpd` from [openbsd/src](https://github.com/openbsd/src). There were no conflicts and it passes on CI (except macOS that is currently broken).
What about openbsd-compat? Some files have been copied from openbsd, but it seems that they haven’t been updated in the past.
How can I verify that everything works fine? I don’t see any tests in this repository…
@poolpOrg
> Sync changes in usr.sbin/smtpd from OpenBSD

- README.md
Added new and modified existing warning about freshness, minor markdown formatting/linting, macOS.
See #1193
Signed-off-by: Art Manion <zmanion@protonmail.com>
> Add freshness warnings, markdown linting

- openbsd-compat/libasr/asr.c
- openbsd-compat/libasr/asr_compat.h
- openbsd-compat/libasr/asr_debug.c
- openbsd-compat/libasr/asr_private.h
- openbsd-compat/libasr/asr_run.3
- openbsd-compat/libasr/asr_utils.c
- openbsd-compat/libasr/getaddrinfo_async.c
- openbsd-compat/libasr/gethostnamadr_async.c
- openbsd-compat/libasr/getnameinfo.c
- openbsd-compat/libasr/getnameinfo_async.c
- openbsd-compat/libasr/getrrsetbyname_async.c
- openbsd-compat/libasr/res_mkquery.c
- openbsd-compat/libasr/res_send_async.c
- openbsd-compat/libasr/thread_private.h
lots of changes imported in one go.  This notably excludes the commit from florian@ to consider the current routing domain.
> start to sync libasr with base

- configure.ac
- mk/smtpd/Makefile.am
and rework a bit how it's detected.
> provide --with-bundled-libasr knob

- usr.sbin/smtpd/smtp_session.c
> Remove check inhibiting parameters on NOOP.

- usr.sbin/smtpd/table.c
discovered & corrected by satanist on IRC
> fix address family typo in table.c (PF_INET->PF_INET6)
