smtpd/filter_api.c

smtpd.c imsg_to_str is the correct version. ctags gets confused and takes us to wrong
definition.

Remove duplicate definition of imsg_to_str.

---

smtpd/queue_backend.c

Receiving this error:
warn: purge_task: opendir: Permission denied
With capability CAP_DAC_OVERRIDE dropped. Root also needs to be able to
access the directory PATH_PURGE.

Fix permissions for directory PATH_PURGE

---

README

- Strip `[name](URL)`
- Wrap long lines (with the exception of commands)
- Remove redundant # in sections

Remove Markdown from the README file

---

smtpd/smtp_session.c
smtpd/ssl.c

SSL_get_cipher_version() returns the version of SSL/TLS that the
ciphersuite was introduced/defined in, not the version in use for
the connection.
Use SSL_get_version() instead.

[TLS] Use correct function to determine session protocol version

---

openbsd-compat/fgetln.c

If return value from getc() is stored in a char, comparison to EOF never
succeeds on some platforms.

fix getc() usage in compat fgetln()

---

configure.ac
openbsd-compat/openbsd-compat.h

Because Solaris don't have AF_LOCAL

check for AF_LOCAL and define to AF_UNIX if not

---

configure.ac
openbsd-compat/openbsd-compat.h

Solaris 10 don't define WAIT_MYPGRP

check for WAIT_MYPGRP

---

smtpd/parse.y

each lines of code using ss_len are surrounded by #if have_struct_sockaddr_storage_ss_len

use ss_len only if exists

---

smtpd/smtp.c

When trying to listen for exanple on both `0.0.0.0` and `::`, the IPv6 listen would fail with "Address already in use" because it's also trying to bind on IPv4 for mapping IPv4 to IPv6.
I'm really not sure how to handle this, but it seems like the other softwares I'm running (Dovecot, NGINX) all explicitly set `IPV6_V6ONLY` to `1` (see for [Dovecot](https://github.com/dovecot/core/blob/7c925149e49f7cce41c90d562ff3835b66ddca29/src/lib/net.c#L445) and [NGINX](https://github.com/nginx/nginx/blob/2ce791f2cddff967fd3bcbbedcd4ea283a9c77e1/src/core/ngx_connection.c#L490)).
This PR adds this option for IPv6 sockets if supported.

set IPV6_V6ONLY if available

---

openbsd-compat/entropy.c

opensmtp checks the openssl version at startup,
but because the check is done wrong using an bad
mask opensmtp doesn't start.
This issue affects FreeBSD 10

fix openssl version check done wrong with an invalid mask

---

configure.ac

Defer checking for arc4random and friends until libcrypto is found,
fixes segv due to portable libressl/opensmtpd and arc4random<->RAND_bytes.
See http://marc.info/?l=openssh-unix-dev&m=140515171616098&w=2
for more information.
This is my first PR attempting to upstream the changes in our package repositories.

Defer finding arc4random until after libcrypto

---

configure.ac
openbsd-compat/defines.h
openbsd-compat/openbsd-compat.h

As explain in
https://www.gnu.org/savannah-checkouts/gnu/autoconf/manual/autoconf-2.69/html_node/Generic-Declarations.html#Generic-Declarations
"Unlike the other `AC_CHECK_*S' macros, when a symbol is not
declared, HAVE_DECL_symbol is defined to `0' instead of
leaving HAVE_DECL_symbol undeclared."

Fix expression

---

configure.ac

On Solaris, inet_aton and inet_ntoa require '-lsocket -lnsl'.
configure.ac can't find this functions:
...
checking for inet_ntoa... no
checking for inet_ntop... no
...
Libraries: -lz -lcrypto -lssl -levent -lasr -lsocket -lfts -lrt -lresolv
Add "--with-libs='-lnsl'" don't fix:
...
checking for inet_ntoa... no
checking for inet_ntop... no
...
Libraries: -lz -lcrypto -lssl -levent -lasr -lsocket -lfts -lrt -lresolv  -lnsl
Because --with-libs is check too late. Move it before 'AC_SEARCH_LIBS' fix the problem:
...
checking for inet_ntoa... yes
checking for inet_ntop... yes
...
Libraries: -lz -lcrypto -lssl -levent -lasr -lsocket -lfts -lrt -lresolv  -lnsl

move --with-libs

---

configure.ac
openbsd-compat/Makefile.am
smtpd/smtpd.c
smtpd/smtpd.h
smtpd/util.c

On Solaris and FreeBSD, closefrom return void. On this systems, the following code is invalid:
if (closefrom(4) == -1)
This patches fix it (inspired by __gilles@)

Xclosefrom

---

configure.ac
openbsd-compat/defines.h

On some Os (Solaris, IllumOS ...) LOG_PERROR does not exists.
Using as bitmask, 0 seems to be a safe value.

fix LOG_PERROR if not exists

---

configure.ac
openbsd-compat/openbsd-compat.h

inet_net_pton is already compiled, but no prototype is provided.
res_hnok is provided by the compatibility layer in libasr.
These fixes avoid warnings about implicit function declaration.
Fixes #758

fix musl compatibility (missing function prototypes)

---

openbsd-compat/defines.h
openbsd-compat/openbsd-compat.h

These functions are exported by libcrypto from libressl, due to its
similar OpenBSD compatibility layer, but they are not present in any
header files. Thus, while we can use the existing compiled function,
and do not need to provide our own, we do need to provide the prototype
for it.
This avoids implicit function declarations and the resulting crashes due
to pointer truncation.
The patch is based on an equivalent patch for OpenSSH from
https://bugzilla.mindrot.org/show_bug.cgi?id=2465
Also see
https://github.com/libressl-portable/portable/issues/109
Fixes #691

fix compatibility with libressl

---

configure.ac
smtpd/smtpctl.c

Fix warning when check for __progname in configure.ac
Fix segfault when using undefined var in smtpctl.c

fix __progname detection/use

---

smtpd/table.c

Right now, if table_dump_lookup is called with a lookup type it cannot handle, eg. K_MADDRMAP,
it will return its static buffer with the contents from previous lookup, which can be very confusing, eg. when I see in the logs a senders table returning a password hash.
This PR fixes it by writing `"???"` to the buffer in the type switch reaches `default`

Fix table_dump_lookup's default case

---

smtpd/table.c

If there's too many addresses to fit in a line (because eg. someone didn't use whitespace in the table), the code puts "..."  at the end of the truncated string.
(in response to #780)

Add K_MAILADDRMAP support to table_dump_lookup

---

openbsd-compat/chacha_private.h

sys/types.h is required by u_int

add missing header

---

openbsd-compat/defines.h

MacOS 10.10 does not implement clock_gettime(), and so is missing the defines
for CLOCK_REALTIME and CLOCK_MONOTONIC. A definition exists for CLOCK_MONOTONIC
in openbsd-compat , but CLOCK_REALTIME was missing.
../../smtpd/queue_fs.c:763:20: error: use of undeclared identifier 'CLOCK_REALTIME'
if (clock_gettime(CLOCK_REALTIME, &startup))
^
1 error generated.
make[3]: *** [../../smtpd/smtpd-queue_fs.o] Error 1

defines.h: Add openbsd-compat define for CLOCK_REALTIME

---

openbsd-compat/crypt_checkpass.c

adding `#include "includes.h"` makes sure, `HAVE_CRYPT_H` is defined if detected by the configure script. This fixes #833.
`crypt(3)` might return `NULL` on error, this should not be passed to `strcmp(3)`

crypt_checkpass: include HAVE_CRYPT_H definition, add NULL check

---

smtpd/spfwalk.c

- remove LINE_MAX (not used)
- pledge is defined in openbsd-compat.h

Fix build portable

---

configure.ac
mk/mail/mail.lmtp/Makefile.am
mk/mail/mail.maildir/Makefile.am
mk/mail/mail.mda/Makefile.am
mk/smtpctl/Makefile.am
mk/smtpd/Makefile.am
openbsd-compat/Makefile.am
openbsd-compat/err_h/err.h
openbsd-compat/paths_h/paths.h
openbsd-compat/xmalloc.c

start split of openbsd-compat
build fine on Solaris who's don't provide err.h nor paths.h

Split openbsd compat

---

mk/smtpctl/Makefile.am

With this change and addition of `CFLAGS=-ffunction-sections` and
`LDFLAGS=-Wl,--gc-sections`, it now builds.
`purge_config` is defined in `config.c` but used in `parse.y`, making
`config.c` mandatory. But `config.c` requires lots of functions from
other files in other unrelated functions, meaning that these unrelated
(and unused in `smtpctl`) functions need to be garbage-collected.
This is a workaround, a better way would likely be to refactor
`purge_config` and `config_default` out of `config.c`, but I don't want
to push for a change that would separate the portable version and the
OpenBSD version too much.

Add missing object file for smtpctl

---

configure.ac

AC_RUN_IFELSE is missing the last argument [action-if-cross-compiling]
See also: https://www.gnu.org/software/autoconf/manual/autoconf-2.68/html_node/Runtime.html

fix cross compilation

---

Dockerfile
README.md

Some versions of docker have problems mounting single files.
Also include directions for using it in the Readme.
Some of the man pages refer to '/etc/mail/smtpd.conf', others to '/etc/smtpd.conf', which is the program's default, and `./configure` defaults to '/usr/local/etc/smtpd.conf'. I'm using '/etc/smtpd/smtpd.conf' because many programs seem to use the smtpd folder.
If you'd like this in a different folder, for example '/etc/mail' it's an easy change.  However leaving the file in just '/etc' wasn't working with docker.

Switch Dockerfile to using /etc/mail/ for all configuration

---

.gitignore
Dockerfile
docker-compose.test.yml
tests/certificate_test/smtpd.conf
tests/certificate_test/test.sh
tests/test_all.sh
tests/test_email.txt

This should allow Docker Hub to act as a CI platform.
NOTE:  This is testing for #908 which means Docker Hub's test should fail until it is resolved.

Add an automated test to check if TLS certificates work

---

docker-compose.test.yml

The test still fails, but this now properly calls the test script.

Fix Docker Hub's autotest not working

---

Dockerfile

Split of  https://github.com/OpenSMTPD/OpenSMTPD/pull/945
Replace libressl with openssl
Fixes the immediate problem of broken docker build.

Fix broken docker build

---

Dockerfile

Alpine Linux updated to 3.10
Rest is style changes:
- package lists sorted
- `&&` are in the beginning of the line (bestpractice, readability)
- removed unnecessary trailing `/` for `mkdir`
- split long lines into smaller ones

dockerfile minor style changes

---

docker/README.md
etc/README.md

@poolpOrg this is how I envisioned a new folder structure.
As discussed in https://github.com/OpenSMTPD/OpenSMTPD/issues/947
We can put configs in `etc/` and dockerfiles and maybe some related scripts in `docker/` to avoid polluting the root of the repo

[RFC] prepare folders for configs and dockerfiles

---

docker/Dockerfile.archlinux

Reproduces https://github.com/OpenSMTPD/OpenSMTPD/issues/958

docker: add explicit flags to use libressl on archlinux

---

.github/workflows/docker.yml
.github/workflows/ubuntu.yml

This exposes #944 #958  to our Actions CI.
Archlinux + libressl build is failing

ci: add archlinux docker build to docker workflow

---

CHANGES.md
README.md
docker/README.md

- add changes file to reflect what is new in 6.6.0 version (as discussed in https://github.com/OpenSMTPD/OpenSMTPD/issues/944)
- all markdown headers are atx style now to allow more then 2 levels (mix of setext and atx does not work well)
- moved docker documentation to docker folder

doc: add 6.6.0 changes and more

---

.gitignore
ci/scripts/clang_scan.sh
ci/scripts/generate_certs.sh
ci/scripts/imports/badge.sh

Script that generates clang `scan-build` report and optionally generates a badge for it.
It will be used in a actions workflow in website repo to publish daily report

ci: clang scan script

---

.builds/README.md

@ddevault confirms that only build manifests are expected in `.builds/` directory
> It looks like presence of other files in .builds/ directory (in my case - 
readme.md) breaks build/dispatch (not sure which one)
>
> You can see it here:
>
>https://github.com/OpenSMTPD/OpenSMTPD/pull/1004
>https://github.com/OpenSMTPD/OpenSMTPD/pull/1005
>
>The PR that removes readme file from the builds/ directory triggers sourcehut 
build. The other one - does not.
```
From:	Drew DeVault <sir@cmpwn.com>
To:	Me
CC:	gilles@poolp.org
Date:	11/25/19 5:28 AM
Aye, this is not supported. You need to leave only build manifests in
your builds directory.
```

ci: remove readme file that breaks srht builds

---

smtpd/mail.lmtp.c

I've added a workaround for the problem discussed in https://github.com/OpenSMTPD/OpenSMTPD/issues/994. Right now it is only tested on alpine linux.

workaround for musl's implementation of fflush() in mail.lmtp

---

smtpd/smtpctl.c

Too many Linux distributions (Debian, Ubuntu, Arch, Fedora) got smtpctl
permissions wrong. The typical pattern (applies to Arch) is:
* The build machine does not have the smtpq group
* The build runs as non-root with --with-group-queue=smtpq
* The smtpq group is created in post-install via systemd-sysusers
* There is nothing that makes smtpctl setgid smtpq
* The package even seems to work until offline delivery is attempted
Let's make sure users complain to the distributors if the above happens,
instead of having a silently broken installation.
See also the (invalid) ticket #1012.

smtpctl: check correct egid at startup

---

openbsd-compat/Makefile.am

In out-of-tree builds anything inside openbsd-compat/ including local files prefixed with smtpd/ are not found, including the source base directory takes care of that.

openbsd-compat: fix out-of-tree builds

---

.builds/freebsd.yml
ci/docker/Dockerfile.alpine

Two things are going on here:
- FreeBSD build on SourceHut is now using my new ansible framework. It covers very small area at the moment - build and simple mail send to a local recipient, but it is easily extendible to include more tests or more platforms. I plan to include all linux builds in the nearest future.
- Alpine container upgraded to 3.11 (latest release) and switched to libressl

ci: ansible testing framework for freebsd build + alpine 3.11 on libressl

---

mk/smtpd/Makefile.am

smtpd.conf(5) in the portable branch refers to the directory `/usr/local/libexec/smtpd/`. This may not be the correct location on non-OpenBSD systems (it is not on Debian). Update the Makefile to update this location at compile time.

Use correct libexec path in portable man pages

---

smtpd/smtpd.conf.5

The man page does not explain what the `junk` decision means when filtering or what happens if you do not have a `Junk` folder. This diff documents this.

Document junking in smtpd.conf(5)

---

openbsd-compat/Makefile.am

From IRC:
```
09:34 < rak> opensmtpd 6.7.0p1 installs /usr/include/asr.h, but doesn't install the corresponding libasr.so file. Is usr/include/asr.h really meant to be installed, or is that a bug?
10:02 < __gilles> rak: its not meant to be installed, that's a bug
```

Do not install asr.h

---

openbsd-compat/pipe2.c

O_CLOEXEC must be enabled with F_SETFD, not F_SETFL. Prior passing
FD_CLOEXEC to F_SETFL resulted in wrong behavior. While we're fixing
this, we can also add support for O_CLOEXEC, which we enable via
F_SETFL.

compat: pipe2: enable O_CLOEXEC correctly and support O_NONBLOCK

---

README.md

Turns out the wiki is disabled due to lack of contribution. This PR updates the link to the wiki to point to [the manual pages link on OpenSMTPD's website](https://www.opensmtpd.org/manual.html) instead.
Closes #1070
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/opensmtpd/opensmtpd/1071)

Replace link to the wiki with a link to the manual pages.

---

usr.sbin/smtpd/smtpctl.c

encrypt.c will exit if `argc > 2`. However, the code at smtpctl.c:L969 executes `encrypt` with wrong number of arguments when `p != NULL`, which leads to a bug that the program complains `usage: encrypt <string>` when we run `smtpctl encrypt some_string`.
The code  `"--", ` was involved in commit `4c624cc`. Before that commit, the code had always been `execl(PATH_ENCRYPT, "encrypt", p, (char *)NULL);`.

fix bug with "smtpctl encrypt"

---

mk/mail/mail.lmtp/Makefile.am
mk/mail/mail.maildir/Makefile.am
mk/mail/mail.mboxfile/Makefile.am
mk/mail/mail.mda/Makefile.am
mk/smtp/Makefile.am
mk/smtpctl/Makefile.am
mk/smtpd/Makefile.am
openbsd-compat/Makefile.am

Automake treats $(top_srcdir) specially, so a variable that expands to
it won't work.  There were also bugs in the Makefile.am files that broke
`make distcheck`

Fix out-of-tree build

---

README.md

Updated the instructions for MacOS X and Big Sur.
Maybe suggest with `--sysconfdir=/etc/mail` ?

Update MacOS instructions

---

configure.ac

Running ${NROFF} on a nonexistent file always fails, leading to the
man pages being instealled to /share/man/catN instead of manN.
This follows up on commit 054cadd5524759b57aefb39659356552091118d9.

configure.ac: Fix man page location.

---

.builds/freebsd.yml

db6 package was removed from ports tree due to it is no longer
downloadable without registration. It is recommended to use db5 instead.
https://www.freshports.org/databases/db6

Fix broken FBSD CI build

---

usr.sbin/smtpd/smtpd.conf

OpenBSD has an "all" interface group that includes all interfaces
(ifconfig(8)), but this interface group does not exist on other systems.
As a result, it doesn't make sense to discuss listening on this
interface in the portable version of OpenSMTPD. Instead, we should
suggest that users listen on the meta-addresses 0.0.0.0 and :: if they
want to receive mail on all interfaces.
Closes: https://bugs.debian.org/963252

Don't mention OpenBSD interface 'all' in portable smtpd.conf

---

README.md

Mention that OpenSMTPD is available from MacPorts in README.md
[skip ci]

Mention that OpenSMTPD is available from MacPorts in README.md

---

configure.ac
openbsd-compat/Makefile.am
openbsd-compat/getsubopt.c
openbsd-compat/openbsd-compat.h

The OpenBSD version of getsubopt has a non portable extention which is used in usr.sbin/smtpd/smtpc.c
Not sure if the configure check should also test for the extention.

add getsubopt to openbsd-compat

---

usr.sbin/smtpd/bounce.c
usr.sbin/smtpd/ca.c
usr.sbin/smtpd/control.c
usr.sbin/smtpd/envelope.c
usr.sbin/smtpd/ioev.c
usr.sbin/smtpd/mda.c
usr.sbin/smtpd/mda_variables.c
usr.sbin/smtpd/mta_session.c
usr.sbin/smtpd/smtp_client.c
usr.sbin/smtpd/smtp_session.c
usr.sbin/smtpd/smtpctl.8
usr.sbin/smtpd/smtpd.8
usr.sbin/smtpd/smtpd.c
usr.sbin/smtpd/smtpd.conf.5

This should bring OpenSMTPD-portable in pair with -CURRENT.  So far I've only build-tested it on OpenBSD and void linux (musl -- needed libbsd too) but as I was about to set up a new mx these days, i'll be able to test it more throughfully on linux soon.
A change from deraadt@ is still missing, but since it's tiny and allows to drop checks from the configure too I'll backport it in a separate PR once this lands: https://github.com/openbsd/src/commit/e16a722a8a965b85c7889b97d3d2e0580039ade0#diff-7e16a1fb5fcbd028a0757ac4fb5f020766f91e02fd50baf2fa5df6cc67ffb82e

sync with CVS

---

configure.ac

Automake provides `AM_PROG_AR` as a standard way of finding `ar(1)`.
Reference: https://www.gnu.org/software/automake/manual/html_node/Public-Macros.html
Closes: https://github.com/OpenSMTPD/OpenSMTPD/pull/1177

configure: Use AM_PROG_AR

---

configure.ac
openbsd-compat/fparseln.c
usr.sbin/smtpd/log.h

This is a backport of a commit from deraadt@ that we were missing, and also removing the now unused check for sys/cdefs.h.  I've also removed the include in fparseln.c, which were removed also by deraadt@ in 2012.

drop sys/cdefs.h checks/includes

---

openbsd-compat/openbsd-compat.h
usr.sbin/smtpd/mail.maildir.c
usr.sbin/smtpd/parse.y
usr.sbin/smtpd/smtpd.c

This has two commits.
1.
On a system with musl these functions are not available, but they are found by the build system inside of libbsd instead. However many of the relevant headers are never incuded resulting in many implicit function declarations. Additionally clang-16 is more strict about these turning them into errors.
2.
Split into PR https://github.com/OpenSMTPD/OpenSMTPD/pull/1198.

build: Fix -Werror=implicit-function-declaration

---

configure.ac

On musl systems `crypt()` is provided by `unistd.h` and it is marked as `"none required"` during the configure process. This results in `-lcrypt` never being passed to the compiler and then an undefined reference for `crypt_gensalt()`. This can be solved by checking for `crypt_gensalt()` instead.

configure.ac: Check for crypt_gensalt()

---

usr.sbin/smtpd/mda_unpriv.c

spotted while looking at the diff with CVS, it was changed by crisz@ in rev. 1.7 with
> Run lmtp deliveries as SMTPD_USER instead of the recipient user.
which was ported, since the other part of that commit (parse.y bits) are in-tree.  I couldn't find in the history when this was exactly backported, sorry!
@poolpOrg just to be sure, can you please take a look?

fix USER and LOGNAME in the env of the mda

---

openbsd-compat/libtls/tls.c

In OpenSSL 3.x due to a behaviour change EVP_PKEY_get1_EC_KEY() returns a cashed copy of the provider's key, so subsequent updates are not reflected back breaking the privsep usage and making the handshake fail with a cryptic "missing private key".  Instead, we have to set the changed key explicitly.
See #1171

libtls: unbreak with OpenSSL 3.x

---

usr.sbin/smtpd/bounce.c
usr.sbin/smtpd/control.c
usr.sbin/smtpd/enqueue.c
usr.sbin/smtpd/mda.c
usr.sbin/smtpd/mta.c
usr.sbin/smtpd/mta_session.c
usr.sbin/smtpd/queue.c
usr.sbin/smtpd/queue_backend.c
usr.sbin/smtpd/queue_fs.c
usr.sbin/smtpd/runq.c
usr.sbin/smtpd/scheduler_ramqueue.c
usr.sbin/smtpd/smtp_session.c
usr.sbin/smtpd/smtpctl.c
usr.sbin/smtpd/smtpd.c
usr.sbin/smtpd/smtpd.h
usr.sbin/smtpd/to.c

@dfateyev could you please give this PR a spin on RHEL7?  Should fix the build failure, although I won't be surprised if it wants `time.h` in smtpd.h.
Thanks!

add missing include of sys/time.h and time.h

---

.github/workflows/alpine-release.yml
ci/docker/Dockerfile.alpine-release

Hello OpenSMTPD team,
I noticed that there were no "official" "source of truth" docker/container images for OpenSMTPD. I would like to propose and help have "official" opensmtpd containers on Github's container registry `ghcr.io/opensmtd/<image>`. 
Currently, I have adapted the `ci` dockerfile for alpine to add the entrypoint, and added the GH runner yaml to parse the tag number and apply it as a tag on the image (taken from github's documentation).
I assume extensive testing will be required (which I haven't gotten around to), opening this PR to open discussion.

Add GH Runner to build images of release tags

---

openbsd-compat/Makefile.am
openbsd-compat/libtls/tls.c
openbsd-compat/libtls/tls.h
openbsd-compat/libtls/tls_config.c
openbsd-compat/libtls/tls_internal.h
openbsd-compat/libtls/tls_signer.c
openbsd-compat/libtls/tls_verify.c

with this we're in sync with the latest libtls from CVS, minor the pthread bits we don't use.  (including the signer APIs this time!)

sync libtls, september 2023 edition

---

README.md

Now that the CI for generating container images and publishing on GHCR is up, we can add this to the README for greater visibility.

Add container image to README

---

configure.ac
openbsd-compat/includes.h
openbsd-compat/openbsd-compat.h

LibreSSL pre 3.8 leaks the symbols of their compats in libcrypto. This is particularly painful with arc4random() which, in our implementation, relies on libcrypto.  LibreSSL' RAND_add() calls itself arc4random_buf() resulting in an infinite loop due to the symbol clash.
Instead, check for arc4random() only after we've found libcrypto, and re-establish the prototype hack in openbsd-compat.h.  Hopefully we'll be able to get rid of this workaround in a few releases.
Issue reported by @graywolf, thank you!
Fixes #1233

work around arc4random() symbol clash with old LibreSSL

---

configure.ac

since ebea68918a we're not "aggressively" depending on libresolv and this caused breakage on macos since the build there relied on the configure script adding -lresolv if found even if apparently not needed.
Now it fails to build since we include resolv.h which has #defines from res_hnok (and b64_{pton,ntop}) to the res_9_* "namespace", and not linking with -lresolve leaves those symbols undefined.
So, check additionally for the res_9_* function names to pull in -lresolv on macos.
Issue reported by @artkiver (グレェ), github issue #1232, thanks!

fix res_hnok and b64_{pton,ntop} on macos

---

openbsd-compat/defines.h

it's not always available on some old darwin versions, so apply a similar treatment that `EAI_NODATA` gets: re-define it as `EAI_FAIL`.
See issue #1246

add compat glue for EAI_OVERFLOW too

---

configure.ac
contrib/libexec/encrypt/Makefile.am
contrib/libexec/lockspool/Makefile.am
contrib/libexec/mail.local/Makefile.am
mk/mail/mail.lmtp/Makefile.am
mk/mail/mail.maildir/Makefile.am
mk/mail/mail.mboxfile/Makefile.am
mk/mail/mail.mda/Makefile.am
mk/smtp/Makefile.am
mk/smtpctl/Makefile.am
mk/smtpd/Makefile.am

We might fail to compile the bundled libtls on some systems because --with-libevent adds to CFLAGS, so we end up using the system' tls.h instead of the bundled one.
Instead of the complete fix for the configure.ac, which is needed but there's not enough time for 7.6, move the -I flags to the various Makefile.am as AM_CPPFLAGS.

Move compat/libtls inclusion in the Makefile.am

---

openbsd-compat/Makefile.am

Hey there, while trying to compile opensmtpd on debian I found that posix_time.h was missing. I couldn't find it in the release tarball of 7.6.0p0, so unless I did something completely wrong it might need to be added?

added missing openbsd-compat/openssl/posix_time.h
